version: "3"

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    volumes:
       - ./Cachet/:/var/www/html/
    build:
      context: .
      args:
        - cachet_ver=2.4
    ports:
      - 80:8000
      - 443:8003
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
      - MAIL_HOST=web2-cpn.biz.net.id
      - MAIL_PORT=25
      - MAIL_USERNAME=tes@demo2-cpn.biz.net.id
      - MAIL_PASSWORD=@Biznetgio2021
      - MAIL_ADDRESS=notification@status.bantuan.cloud
      - MAIL_NAME=StatusPage
    depends_on:
      - postgres
    restart: on-failure
